name: CI
on:
  pull_request:
  push:
    branches:
      - main

env:
  MIX_ENV: test

jobs:
  mix_test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.12"
              otp: "24.x"
          - pair:
              elixir: "1.15.4"
              otp: "26.x"
            lint: lint

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-deps
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: deps-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-
      - uses: actions/cache@v3
        with:
          path: _build
          key: build-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: build-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install and compile dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix do deps.get --only test, deps.compile

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Check for unused dependencies
        run: mix do deps.get, deps.unlock --check-unused
        if: ${{ matrix.lint && steps.cache-deps.outputs.cache-hit != 'true'}}

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run Tests
        run: mix test
        if: ${{ ! matrix.lint }}

      - name: Run Tests
        run: mix test
        if: ${{ matrix.lint }}
